services:
  postgres:
    image: pgvector/pgvector:pg16    
    environment:
      - POSTGRES_PASSWORD=El9KwQjjsd79zETMvac55SOfZTUa5xzN
      - TZ=America/Sao_Paulo
    networks:
      - portainer_default    
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager         
      resources:
        limits:
          cpus: "1"
          memory: 2048M

volumes:
  postgres_data:
    external: true
    name: postgres_data

networks:
  portainer_default:
    external: true
    name: portainer_default