services:
  redis:
    image: redis:latest
    command: [
        "redis-server",
        "--appendonly",
        "yes",
        "--port",
        "6379",
        "--requirepass",
        "El9KwQjjsd79zETMvac55SOfZTUa5xzN"
      ]
    volumes:
      - redis_data:/data
    networks:
      - portainer_default
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 2048M

volumes:
  redis_data:
    external: true
    name: redis_data

networks:
  portainer_default:
    external: true
    name: portainer_default
